### ISSUE TITLE
need study material

### ISSUE THREAD

**Issue by somiyaa** [bassamarshad/CBIR--Content-Based-Image-Retrieval#1]
hi

I find your project really helpful and I am going to refer this in my thesis. would you be able to send me the study material related to this project?

**Comment by bassamarshad** [comment]
Hi,

Glad you are interested in citing my work in your thesis.

Basically, the contribution here is the downsampling of the HSV domain
pixel resolution to a more manageable 8-bit (4-2-2) feature vector. This
helps in the histogram comparison.

There isn't a lot of study material apart from the source code ... It's a
straightforward approach actually ... I haven't implemented this in OpenCV
(where you could get a larger array of histogram comparison techniques).
What you can do and I thought about as extension work (never got a chance
to pursue this) - use machine learning algorithms like kNN or SVM to do the
classification or nearest neighbor searching.

I have a ppt -
https://docs.google.com/presentation/d/1m5P6-pJyF2uELV0BCBqQ30ViisyGenLuVmBcfIfuJtA/edit?usp=sharing




-Bassam

**Comment by bassamarshad** [comment]
more literature related to this project :

https://drive.google.com/drive/folders/0B23LG87Skiwffjd1NGhJNEZpaGNudlk0YjZiaTRCQks0blQzR3dlOWhoTmp0N29MOFVyWXM

**Comment by somiyaa** [comment]
thanks for the help and suggestion. 👍  🥇 :-)
